version: '3'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    env_file: ./.env
  php:
    build: ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/html/.env
      - ./html:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=$PMA_USER
      - PMA_PASSWORD=$PMA_PASSWORD
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    env_file: ./.env
