version: '3'

services:
  mysql:
    build:
      context: ./.docker/mysql
      dockerfile: Dockerfile
    container_name: blog_mysql
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    env_file: ./.env
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: blog_php
    restart: always
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/html/.env
      - ./html:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog_phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    ports:
      - 4040:80
    volumes:
      - ./.docker/phpmyadmin/sessions:/sessions
    env_file: ./.env
volumes:
  db-store:
